env:
  es2020: true
  node: true
extends:
  - standard
  - plugin:@typescript-eslint/recommended
  - plugin:unicorn/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/explicit-function-return-type': off
  'unicorn/prefer-top-level-await': off
  'unicorn/no-null': off
  'no-console': error
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    rules:
      '@typescript-eslint/explicit-function-return-type':
        - error
        - { allowExpressions: true }
