printWidth: 80
tabWidth: 2
useTabs: false
semi: false
quoteProps: 'as-needed'
singleQuote: true
jsxSingleQuote: true
trailingComma: 'es5'
bracketSpacing: true
bracketSameLine: true
arrowParens: 'always'
endOfLine: lf